---
title: "Used Car Catalog"
author: Utkal Sirikonda
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny

---

```{r setup, include=FALSE, message=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(DT)
library(tidyverse)
library(car)
library(rsconnect)
```


```{r}
input_data <- read.csv("cars.csv", header = TRUE, stringsAsFactors = FALSE)

processed_data <- input_data %>%
  drop_na(manufacturer_name, model_name, year_produced)

processed_data <- processed_data %>%
  mutate(across(c(engine_has_gas, has_warranty, is_exchangeable,starts_with("feature_")), 
                ~ . == "True"))

processed_data <- processed_data %>%
  mutate(feature_count = rowSums(select(., starts_with("feature_"))))

processed_data <- processed_data %>%
  select(manufacturer_name, model_name, year_produced, 
         engine_type, engine_capacity, transmission, 
         body_type, drivetrain, color, mileage = odometer_value, engine_fuel,state,location_region,number_of_photos,
         price_usd, has_warranty, is_exchangeable,duration_listed,up_counter, feature_count)

```


```{r}
selectInput("manufacturer", "Choose Manufacturer:",
            choices = unique(processed_data$manufacturer_name),
            selected = "Subaru")

sliderInput("year_range", "Year Produced:",
            min = min(processed_data$year_produced),
            max = max(processed_data$year_produced),
            value = c(2000, 2020),
            step = 1)
```


Column {.tabset}
-------------------------

### Graph
```{r}
filtered_data <- reactive({
  processed_data %>%
    filter(
      manufacturer_name == input$manufacturer,
      year_produced >= input$year_range[1],
      year_produced <= input$year_range[2]
    )
})

renderPlot({
  ggplot(filtered_data(), aes(x = mileage, y = price_usd)) +
    geom_point(alpha = 0.6, color = "steelblue") +
    labs(
      title = paste("Mileage vs Price -", input$manufacturer),
      x = "Mileage (km)", y = "Price (USD)"
    ) +
    theme_minimal()
})
```

### Data Table
```{r}
renderDataTable({
  filtered_data()
})

```

